//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.04.15 at 05:22:24 PM CEST 
//


package nl.chb.psa;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{}quays"/&gt;
 *         &lt;element ref="{}stopplaces"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "quays",
    "stopplaces"
})
@XmlRootElement(name = "export")
public class Export {

    @XmlElement(required = true)
    protected Quays quays;
    @XmlElement(required = true)
    protected Stopplaces stopplaces;

    /**
     * Gets the value of the quays property.
     * 
     * @return
     *     possible object is
     *     {@link Quays }
     *     
     */
    public Quays getQuays() {
        return quays;
    }

    /**
     * Sets the value of the quays property.
     * 
     * @param value
     *     allowed object is
     *     {@link Quays }
     *     
     */
    public void setQuays(Quays value) {
        this.quays = value;
    }

    /**
     * Gets the value of the stopplaces property.
     * 
     * @return
     *     possible object is
     *     {@link Stopplaces }
     *     
     */
    public Stopplaces getStopplaces() {
        return stopplaces;
    }

    /**
     * Sets the value of the stopplaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stopplaces }
     *     
     */
    public void setStopplaces(Stopplaces value) {
        this.stopplaces = value;
    }

}
